# Samuel Adamson (giibbu)
# Portfolio Page
# Load Metrics -- Main

# import base image
FROM google/cloud-sdk:latest

# set working directory
WORKDIR /app

# copy source to working directory
COPY . /app

# install requirements
RUN pip install --no-cache-dir -r requirements.txt
